# coding: utf-8

"""
    Tenant API

    Tenant API

    The version of the OpenAPI document: 0.0.1
    Contact: abc@layer.fr
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json
import importlib

from datetime import datetime
from typing import Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr
from typing import Dict, Any
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CostStats(BaseModel):
    """
    CostStats
    """
    total: Optional[Union[StrictFloat, StrictInt]] = None
    cumulative: Optional[List[Union[StrictFloat, StrictInt]]] = None
    budget: Optional[List[Union[StrictFloat, StrictInt]]] = None
    budget_lower_projection: Optional[List[Union[StrictFloat, StrictInt]]] = None
    budget_upper_projection: Optional[List[Union[StrictFloat, StrictInt]]] = None
    period: Optional[List[datetime]] = None
    projection_period: Optional[List[datetime]] = None
    type: Optional[StrictStr] = None
    by_type: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = None
    __properties: ClassVar[List[str]] = ["total", "cumulative", "budget", "budget_lower_projection", "budget_upper_projection", "period", "projection_period", "type", "by_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CostStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        """Create an instance of CostStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "cumulative": obj.get("cumulative"),
            "budget": obj.get("budget"),
            "budget_lower_projection": obj.get("budget_lower_projection"),
            "budget_upper_projection": obj.get("budget_upper_projection"),
            "period": obj.get("period"),
            "projection_period": obj.get("projection_period"),
            "type": obj.get("type"),
            "by_type": obj.get("by_type")
        })
        return _obj


