/*
Tenant API

Tenant API

API version: 0.0.1
Contact: abc@layer.fr
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package graalsystems

import (
	"encoding/json"
	"fmt"
)

// checks if the ParquetReader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ParquetReader{}

// ParquetReader struct for ParquetReader
type ParquetReader struct {
	// Define file type for PARQUET.
	Type *string `json:"type,omitempty"`
	// Path to PARQUET file.
	Path string `json:"path"`
}

type _ParquetReader ParquetReader

// NewParquetReader instantiates a new ParquetReader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewParquetReader(path string) *ParquetReader {
	this := ParquetReader{}
	var type_ string = "parquet"
	this.Type = &type_
	this.Path = path
	return &this
}

// NewParquetReaderWithDefaults instantiates a new ParquetReader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewParquetReaderWithDefaults() *ParquetReader {
	this := ParquetReader{}
	var type_ string = "parquet"
	this.Type = &type_
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ParquetReader) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ParquetReader) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ParquetReader) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ParquetReader) SetType(v string) {
	o.Type = &v
}

// GetPath returns the Path field value
func (o *ParquetReader) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ParquetReader) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ParquetReader) SetPath(v string) {
	o.Path = v
}

func (o ParquetReader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ParquetReader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *ParquetReader) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varParquetReader := _ParquetReader{}

	err = json.Unmarshal(bytes, &varParquetReader)

	if err != nil {
		return err
	}

	*o = ParquetReader(varParquetReader)

	return err
}

type NullableParquetReader struct {
	value *ParquetReader
	isSet bool
}

func (v NullableParquetReader) Get() *ParquetReader {
	return v.value
}

func (v *NullableParquetReader) Set(val *ParquetReader) {
	v.value = val
	v.isSet = true
}

func (v NullableParquetReader) IsSet() bool {
	return v.isSet
}

func (v *NullableParquetReader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableParquetReader(val *ParquetReader) *NullableParquetReader {
	return &NullableParquetReader{value: val, isSet: true}
}

func (v NullableParquetReader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableParquetReader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


