/*
Tenant API

Tenant API

API version: 0.0.1
Contact: abc@layer.fr
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the StarburstOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StarburstOptions{}

// StarburstOptions struct for StarburstOptions
type StarburstOptions struct {
	DataWarehouseOptions
	Env *map[string]string `json:"env,omitempty"`
	InstanceType *string `json:"instance_type,omitempty"`
	Type *string `json:"type,omitempty"`
	Licence *string `json:"licence,omitempty"`
	NumberWorkers *float32 `json:"number_workers,omitempty"`
	DatabaseInstanceType *string `json:"database_instance_type,omitempty"`
	DatabaseType *string `json:"database_type,omitempty"`
	Conf map[string]map[string]interface{} `json:"conf,omitempty"`
}

// NewStarburstOptions instantiates a new StarburstOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStarburstOptions() *StarburstOptions {
	this := StarburstOptions{}
	var type_ string = "starburst"
	this.Type = &type_
	return &this
}

// NewStarburstOptionsWithDefaults instantiates a new StarburstOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStarburstOptionsWithDefaults() *StarburstOptions {
	this := StarburstOptions{}
	var type_ string = "starburst"
	this.Type = &type_
	return &this
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *StarburstOptions) GetEnv() map[string]string {
	if o == nil || IsNil(o.Env) {
		var ret map[string]string
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetEnvOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *StarburstOptions) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given map[string]string and assigns it to the Env field.
func (o *StarburstOptions) SetEnv(v map[string]string) {
	o.Env = &v
}

// GetInstanceType returns the InstanceType field value if set, zero value otherwise.
func (o *StarburstOptions) GetInstanceType() string {
	if o == nil || IsNil(o.InstanceType) {
		var ret string
		return ret
	}
	return *o.InstanceType
}

// GetInstanceTypeOk returns a tuple with the InstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.InstanceType) {
		return nil, false
	}
	return o.InstanceType, true
}

// HasInstanceType returns a boolean if a field has been set.
func (o *StarburstOptions) HasInstanceType() bool {
	if o != nil && !IsNil(o.InstanceType) {
		return true
	}

	return false
}

// SetInstanceType gets a reference to the given string and assigns it to the InstanceType field.
func (o *StarburstOptions) SetInstanceType(v string) {
	o.InstanceType = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *StarburstOptions) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *StarburstOptions) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *StarburstOptions) SetType(v string) {
	o.Type = &v
}

// GetLicence returns the Licence field value if set, zero value otherwise.
func (o *StarburstOptions) GetLicence() string {
	if o == nil || IsNil(o.Licence) {
		var ret string
		return ret
	}
	return *o.Licence
}

// GetLicenceOk returns a tuple with the Licence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetLicenceOk() (*string, bool) {
	if o == nil || IsNil(o.Licence) {
		return nil, false
	}
	return o.Licence, true
}

// HasLicence returns a boolean if a field has been set.
func (o *StarburstOptions) HasLicence() bool {
	if o != nil && !IsNil(o.Licence) {
		return true
	}

	return false
}

// SetLicence gets a reference to the given string and assigns it to the Licence field.
func (o *StarburstOptions) SetLicence(v string) {
	o.Licence = &v
}

// GetNumberWorkers returns the NumberWorkers field value if set, zero value otherwise.
func (o *StarburstOptions) GetNumberWorkers() float32 {
	if o == nil || IsNil(o.NumberWorkers) {
		var ret float32
		return ret
	}
	return *o.NumberWorkers
}

// GetNumberWorkersOk returns a tuple with the NumberWorkers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetNumberWorkersOk() (*float32, bool) {
	if o == nil || IsNil(o.NumberWorkers) {
		return nil, false
	}
	return o.NumberWorkers, true
}

// HasNumberWorkers returns a boolean if a field has been set.
func (o *StarburstOptions) HasNumberWorkers() bool {
	if o != nil && !IsNil(o.NumberWorkers) {
		return true
	}

	return false
}

// SetNumberWorkers gets a reference to the given float32 and assigns it to the NumberWorkers field.
func (o *StarburstOptions) SetNumberWorkers(v float32) {
	o.NumberWorkers = &v
}

// GetDatabaseInstanceType returns the DatabaseInstanceType field value if set, zero value otherwise.
func (o *StarburstOptions) GetDatabaseInstanceType() string {
	if o == nil || IsNil(o.DatabaseInstanceType) {
		var ret string
		return ret
	}
	return *o.DatabaseInstanceType
}

// GetDatabaseInstanceTypeOk returns a tuple with the DatabaseInstanceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetDatabaseInstanceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DatabaseInstanceType) {
		return nil, false
	}
	return o.DatabaseInstanceType, true
}

// HasDatabaseInstanceType returns a boolean if a field has been set.
func (o *StarburstOptions) HasDatabaseInstanceType() bool {
	if o != nil && !IsNil(o.DatabaseInstanceType) {
		return true
	}

	return false
}

// SetDatabaseInstanceType gets a reference to the given string and assigns it to the DatabaseInstanceType field.
func (o *StarburstOptions) SetDatabaseInstanceType(v string) {
	o.DatabaseInstanceType = &v
}

// GetDatabaseType returns the DatabaseType field value if set, zero value otherwise.
func (o *StarburstOptions) GetDatabaseType() string {
	if o == nil || IsNil(o.DatabaseType) {
		var ret string
		return ret
	}
	return *o.DatabaseType
}

// GetDatabaseTypeOk returns a tuple with the DatabaseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetDatabaseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DatabaseType) {
		return nil, false
	}
	return o.DatabaseType, true
}

// HasDatabaseType returns a boolean if a field has been set.
func (o *StarburstOptions) HasDatabaseType() bool {
	if o != nil && !IsNil(o.DatabaseType) {
		return true
	}

	return false
}

// SetDatabaseType gets a reference to the given string and assigns it to the DatabaseType field.
func (o *StarburstOptions) SetDatabaseType(v string) {
	o.DatabaseType = &v
}

// GetConf returns the Conf field value if set, zero value otherwise.
func (o *StarburstOptions) GetConf() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Conf) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Conf
}

// GetConfOk returns a tuple with the Conf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StarburstOptions) GetConfOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conf) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Conf, true
}

// HasConf returns a boolean if a field has been set.
func (o *StarburstOptions) HasConf() bool {
	if o != nil && !IsNil(o.Conf) {
		return true
	}

	return false
}

// SetConf gets a reference to the given map[string]map[string]interface{} and assigns it to the Conf field.
func (o *StarburstOptions) SetConf(v map[string]map[string]interface{}) {
	o.Conf = v
}

func (o StarburstOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StarburstOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedDataWarehouseOptions, errDataWarehouseOptions := json.Marshal(o.DataWarehouseOptions)
	if errDataWarehouseOptions != nil {
		return map[string]interface{}{}, errDataWarehouseOptions
	}
	errDataWarehouseOptions = json.Unmarshal([]byte(serializedDataWarehouseOptions), &toSerialize)
	if errDataWarehouseOptions != nil {
		return map[string]interface{}{}, errDataWarehouseOptions
	}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.InstanceType) {
		toSerialize["instance_type"] = o.InstanceType
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Licence) {
		toSerialize["licence"] = o.Licence
	}
	if !IsNil(o.NumberWorkers) {
		toSerialize["number_workers"] = o.NumberWorkers
	}
	if !IsNil(o.DatabaseInstanceType) {
		toSerialize["database_instance_type"] = o.DatabaseInstanceType
	}
	if !IsNil(o.DatabaseType) {
		toSerialize["database_type"] = o.DatabaseType
	}
	if !IsNil(o.Conf) {
		toSerialize["conf"] = o.Conf
	}
	return toSerialize, nil
}

type NullableStarburstOptions struct {
	value *StarburstOptions
	isSet bool
}

func (v NullableStarburstOptions) Get() *StarburstOptions {
	return v.value
}

func (v *NullableStarburstOptions) Set(val *StarburstOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableStarburstOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableStarburstOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStarburstOptions(val *StarburstOptions) *NullableStarburstOptions {
	return &NullableStarburstOptions{value: val, isSet: true}
}

func (v NullableStarburstOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStarburstOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


