/*
Tenant API

Tenant API

API version: 0.0.1
Contact: abc@layer.fr
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the PrintTask type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrintTask{}

// PrintTask Defines a task in a DAG.  Attributes ---------- id : str     Identifier of a task. params : Params     Parameters of a task.  Methods ------- accept(visitor)     Visit a task using a specified visitor. to_node()     Returns the information about the task (id and parameters). to_edge()     Gets all the dependencies of the task.
type PrintTask struct {
	// Identifier of the task.
	Id string `json:"id"`
	Params *PrintParams `json:"params,omitempty"`
	// List of all dependencies of the task.
	Dependency []string `json:"dependency"`
	// Type of the printtask.
	Type *string `json:"type,omitempty"`
}

type _PrintTask PrintTask

// NewPrintTask instantiates a new PrintTask object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrintTask(id string, dependency []string) *PrintTask {
	this := PrintTask{}
	this.Id = id
	this.Dependency = dependency
	var type_ string = "print"
	this.Type = &type_
	return &this
}

// NewPrintTaskWithDefaults instantiates a new PrintTask object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintTaskWithDefaults() *PrintTask {
	this := PrintTask{}
	var type_ string = "print"
	this.Type = &type_
	return &this
}

// GetId returns the Id field value
func (o *PrintTask) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrintTask) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrintTask) SetId(v string) {
	o.Id = v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *PrintTask) GetParams() PrintParams {
	if o == nil || IsNil(o.Params) {
		var ret PrintParams
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintTask) GetParamsOk() (*PrintParams, bool) {
	if o == nil || IsNil(o.Params) {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *PrintTask) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given PrintParams and assigns it to the Params field.
func (o *PrintTask) SetParams(v PrintParams) {
	o.Params = &v
}

// GetDependency returns the Dependency field value
func (o *PrintTask) GetDependency() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Dependency
}

// GetDependencyOk returns a tuple with the Dependency field value
// and a boolean to check if the value has been set.
func (o *PrintTask) GetDependencyOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dependency, true
}

// SetDependency sets field value
func (o *PrintTask) SetDependency(v []string) {
	o.Dependency = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PrintTask) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrintTask) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PrintTask) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PrintTask) SetType(v string) {
	o.Type = &v
}

func (o PrintTask) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrintTask) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	toSerialize["dependency"] = o.Dependency
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

func (o *PrintTask) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"dependency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrintTask := _PrintTask{}

	err = json.Unmarshal(bytes, &varPrintTask)

	if err != nil {
		return err
	}

	*o = PrintTask(varPrintTask)

	return err
}

type NullablePrintTask struct {
	value *PrintTask
	isSet bool
}

func (v NullablePrintTask) Get() *PrintTask {
	return v.value
}

func (v *NullablePrintTask) Set(val *PrintTask) {
	v.value = val
	v.isSet = true
}

func (v NullablePrintTask) IsSet() bool {
	return v.isSet
}

func (v *NullablePrintTask) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrintTask(val *PrintTask) *NullablePrintTask {
	return &NullablePrintTask{value: val, isSet: true}
}

func (v NullablePrintTask) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrintTask) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


